"""empty message

Revision ID: 4f1d0dc86489
Revises: 
Create Date: 2022-01-27 19:51:29.544440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1d0dc86489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_label', sa.String(), nullable=False),
    sa.Column('unit_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_duration', sa.Integer(), nullable=False),
    sa.Column('reminder_delay', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_type')
    # ### end Alembic commands ###
