version: "3.8"

services:
  postgresql:
    image: postgres:14
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_NAME=mental-unload
      - POSTGRES_USER=mental-unload
      - POSTGRES_PASSWORD=mental-unload
    networks:
      - default
  api:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    depends_on:
      - postgresql
    volumes:
      - ./app:/var/www/flask/app
      - ./requirements.txt:/var/www/flask/requirements.txt
      - ./mental_unload.py:/var/www/flask/mental_unload.py
      - ./config.py:/var/www/flask/config.py
    ports:
      - 80:5000
    env_file:
      - .env
    networks:
      - default

