"""empty message

Revision ID: 2481ef49ace9
Revises: 23ce40578747
Create Date: 2022-02-10 08:50:11.365200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2481ef49ace9'
down_revision = '23ce40578747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event', 'event_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'type_id')
    # ### end Alembic commands ###
